### ISSUE TITLE
代码null

### ISSUE THREAD

**Issue by huawei666888** [aroundchange/Spider-RentHouse#1]
from bs4 import BeautifulSoup  # 网页解析，获取数据
ModuleNotFoundError: No module named 'bs4'

**Comment by aroundchange** [comment]
这是Python导入包过程常见的问题，大部分情况下和版本有关，解决链接如下：


https://blog.csdn.net/qq_37811638/article/details/83176748?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165280534616781435475005%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165280534616781435475005&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-83176748-null-null.142^v10^control,157^v4^control&utm_term=ModuleNotFoundError%3A+No+module+named+bs4&spm=1018.2226.3001.4187

还未解决欢迎再联系我！

**Comment by aroundchange** [comment]
> 

这是Python导入包过程常见的问题，大部分情况下和版本有关，解决链接如下：


https://blog.csdn.net/qq_37811638/article/details/83176748?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165280534616781435475005%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165280534616781435475005&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-83176748-null-null.142^v10^control,157^v4^control&utm_term=ModuleNotFoundError%3A+No+module+named+bs4&spm=1018.2226.3001.4187

还未解决欢迎再联系我！

**Comment by huawei666888** [comment]
之前问题解决了，又出现另一个报错

PS C:\TestCode> & C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
Traceback (most recent call last):
  File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in <module>
    import xlwt  # 进行Excel操作
ModuleNotFoundError: No module named 'xlwt'
PS C:\TestCode>

**Comment by huawei666888** [comment]
可以爬取网站数据了，请问保存的excel路径在什么位置

**Comment by aroundchange** [comment]
还是包的问题，这种错误的处理很简单，一般更换版本或者镜像都能解决，下次遇到可以尝试一下，或者将报错信息在CSDN里搜索，较为容易解决。



在 2022-05-18 16:09:07，"Python&集成开发工程师" ***@***.***> 写道：

之前问题解决了，又出现另一个报错

PS C:\TestCode> & C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
Traceback (most recent call last):
File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in
import xlwt # 进行Excel操作
ModuleNotFoundError: No module named 'xlwt'
PS C:\TestCode>

**Comment by aroundchange** [comment]
保存的路径就在根目录下，也可以在自定义函数里修改路径和保存的Excel文件名，见附件标注。
















在 2022-05-18 16:54:57，"Python&集成开发工程师" ***@***.***> 写道：

可以爬取网站数据了，请问保存的excel路径在什么位置

**Comment by huawei666888** [comment]
问题解决了、谢谢了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




 保存的路径就在根目录下，也可以在自定义函数里修改路径和保存的Excel文件名，见附件标注。
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 在 2022-05-18 16:54:57，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：
 
 可以爬取网站数据了，请问保存的excel路径在什么位置

**Comment by huawei666888** [comment]
解决了，谢谢支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




 还是包的问题，这种错误的处理很简单，一般更换版本或者镜像都能解决，下次遇到可以尝试一下，或者将报错信息在CSDN里搜索，较为容易解决。
 
 
 
 在 2022-05-18 16:09:07，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：
 
 之前问题解决了，又出现另一个报错
 
 PS C:\TestCode&gt; &amp; C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
 Traceback (most recent call last):
 File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in
 import xlwt # 进行Excel操作
 ModuleNotFoundError: No module named 'xlwt'
 PS C:\TestCode&gt;

**Comment by aroundchange** [comment]
在 2022-05-18 18:06:54，"Python&集成开发工程师" ***@***.***> 写道：

问题解决了、谢谢了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




保存的路径就在根目录下，也可以在自定义函数里修改路径和保存的Excel文件名，见附件标注。
















在 2022-05-18 16:54:57，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：

可以爬取网站数据了，请问保存的excel路径在什么位置

**Comment by aroundchange** [comment]
OK
















在 2022-05-18 18:06:54，"Python&集成开发工程师" ***@***.***> 写道：

问题解决了、谢谢了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




保存的路径就在根目录下，也可以在自定义函数里修改路径和保存的Excel文件名，见附件标注。
















在 2022-05-18 16:54:57，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：

可以爬取网站数据了，请问保存的excel路径在什么位置

**Comment by aroundchange** [comment]
OK
















在 2022-05-18 18:07:43，"Python&集成开发工程师" ***@***.***> 写道：

解决了，谢谢支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




还是包的问题，这种错误的处理很简单，一般更换版本或者镜像都能解决，下次遇到可以尝试一下，或者将报错信息在CSDN里搜索，较为容易解决。



在 2022-05-18 16:09:07，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：

之前问题解决了，又出现另一个报错

PS C:\TestCode&gt; &amp; C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
Traceback (most recent call last):
File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in
import xlwt # 进行Excel操作
ModuleNotFoundError: No module named 'xlwt'
PS C:\TestCode&gt;

**Comment by aroundchange** [comment]
觉得对你有帮助的话，Github上麻烦给个follow和star，感谢！
















在 2022-05-18 18:07:43，"Python&集成开发工程师" ***@***.***> 写道：

解决了，谢谢支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




还是包的问题，这种错误的处理很简单，一般更换版本或者镜像都能解决，下次遇到可以尝试一下，或者将报错信息在CSDN里搜索，较为容易解决。



在 2022-05-18 16:09:07，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：

之前问题解决了，又出现另一个报错

PS C:\TestCode&gt; &amp; C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
Traceback (most recent call last):
File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in
import xlwt # 进行Excel操作
ModuleNotFoundError: No module named 'xlwt'
PS C:\TestCode&gt;

**Comment by huawei666888** [comment]
OK



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 晚上7:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




 觉得对你有帮助的话，Github上麻烦给个follow和star，感谢！
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 在 2022-05-18 18:07:43，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：
 
 解决了，谢谢支持
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2022年5月18日(周三) 下午5:40
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)
 
 
 
 
 还是包的问题，这种错误的处理很简单，一般更换版本或者镜像都能解决，下次遇到可以尝试一下，或者将报错信息在CSDN里搜索，较为容易解决。
 
 
 
 在 2022-05-18 16:09:07，"Python&amp;amp;集成开发工程师" ***@***.***&amp;gt; 写道：
 
 之前问题解决了，又出现另一个报错
 
 PS C:\TestCode&amp;gt; &amp;amp; C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
 Traceback (most recent call last):
 File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in
 import xlwt # 进行Excel操作
 ModuleNotFoundError: No module named 'xlwt'
 PS C:\TestCode&amp;gt;

**Comment by aroundchange** [comment]
这是Python导入包过程常见的问题，大部分情况下和版本有关，解决链接如下：



https://blog.csdn.net/qq_37811638/article/details/83176748?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165280534616781435475005%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165280534616781435475005&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-83176748-null-null.142^v10^control,157^v4^control&utm_term=ModuleNotFoundError%3A+No+module+named+bs4&spm=1018.2226.3001.4187


还未解决欢迎再联系我！
















在 2022-05-17 23:52:42，"Developer.gordon.gao" ***@***.***> 写道：

from bs4 import BeautifulSoup # 网页解析，获取数据
ModuleNotFoundError: No module named 'bs4'

**Comment by aroundchange** [comment]
在 2022-05-18 18:07:43，"Python&集成开发工程师" ***@***.***> 写道：

解决了，谢谢支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aroundchange/Spider-RentHouse] 代码null (Issue #1)




还是包的问题，这种错误的处理很简单，一般更换版本或者镜像都能解决，下次遇到可以尝试一下，或者将报错信息在CSDN里搜索，较为容易解决。



在 2022-05-18 16:09:07，"Python&amp;集成开发工程师" ***@***.***&gt; 写道：

之前问题解决了，又出现另一个报错

PS C:\TestCode&gt; &amp; C:/Users/gordo/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/TestCode/Spider-RentHouse-main/Spider-RentHouse.py
Traceback (most recent call last):
File "c:\TestCode\Spider-RentHouse-main\Spider-RentHouse.py", line 11, in
import xlwt # 进行Excel操作
ModuleNotFoundError: No module named 'xlwt'
PS C:\TestCode&gt;
